sudo: true  # To use travis container infrastructure

before_install:
  - sudo apt-get install libblas-dev
  - sudo apt-get install liblapack-dev

language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"

before_install:
  - pip install codecov pytest-cov

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install joblib
  - pip install hrf_estimation
  - python setup.py install

# command to run tests
script:
  - coverage run -m pytest

after_success:
  - codecov
